### ISSUE TITLE
Loosing drop cursor functionality

### ISSUE THREAD

**Issue by larafale** [congyaqwq/tiptap-react-image-resize#1]
with tiptap `starterkit`,  out of the box, you can drag and drop images and re drop them anywhere in the document.
I believe the `Image` & `Dropcursor` are responsible for it.

But using this extension, images loose that ability to be moved inside the document.

maybe I'm missing a config param ? i do have `draggable: true` in `Image.extend()`

**Comment by congyaqwq** [comment]
> with tiptap `starterkit`, out of the box, you can drag and drop images and re drop them anywhere in the document. I believe the `Image` & `Dropcursor` are responsible for it.
> 
> But using this extension, images loose that ability to be moved inside the document.
> 
> maybe I'm missing a config param ? i do have `draggable: true` in `Image.extend()`

Sorry for the inconvenience. I will try my best to fix it during my vacation.recently I have been busy with work.

**Comment by congyaqwq** [comment]
https://tiptap.dev/docs/editor/guide/node-views/react#dragging
Sorry, I left an attribute, fixed in 1.1.4, but parent element has some error style, I will fixed it in next version quickly.

**Comment by congyaqwq** [comment]
fixed in version 1.2.2
